version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_NAME=$APP_NAME
      - APP_PORT=$APP_PORT
      - APP_PREFIX=$APP_PREFIX
      - APP_URL=$APP_URL
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - SECRET_KEY=$SECRET_KEY
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: