version: '3.9'
services:
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "${DB_PORT}:3306"
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
  web:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"